apiVersion: v1
kind: Namespace
metadata:
  name: project-argus
  labels:
    name: project-argus
    app: border-detection
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: argus-resource-quota
  namespace: project-argus
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"